### PR TITLE
Added --enable-tests and --enable-benchmarks to configure

### PR DESCRIPTION
**Pull request by ch1bo**
This allows to handle modules/packages of benchmarks and tests as well.
Solves #17

### CODE REVIEW

**Comment by schell** [comment]
@ch1bo - now we've got some conflicts!

**Comment by ch1bo** [comment]
well, @dan-t was faster (PR #21) and this PR is irrelevant then, also issue #17 should be closed

**Comment by dan-t** [comment]
Sorry, I just wanted to get this into the next hdevtools release.

**Comment by schell** [comment]
No worries! Thanks for your help.

**Comment by ch1bo** [comment]
No problem. Shouldve made a PR when fixing it a month ago ;)

**Pull request closed without merging**
